### ISSUE TITLE
Exception in thread "Thread-8" java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 0

### ISSUE THREAD

**Issue by kaisar149** [sharn25/Anime-DL#3]
tried browsing an anime and this showed up on the cmd while showing loading.

D:\AnimeDL>java -jar Anime_DL_7.4.jar
[INFO] MainWindow : Loaded saved Config...
[INFO] StaticResource_VLClibsload : VLC Libs loaded Successfuly
[INFO] StaticResource_FFMPEGlibsload : FFMPEG Libs loaded Successfuly
[INFO] Fetch_Update : No update needed.
Exception in thread "Thread-8" java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
        at java.base/java.util.Objects.checkIndex(Unknown Source)
        at java.base/java.util.ArrayList.get(Unknown Source)
        at com.sb.an_dl.Fetcher.aphelper(Fetcher.java:745)
        at com.sb.an_dl.MainWindow$4$1.run(MainWindow.java:532)

**Comment by kaisar149** [comment]
ok, it was a server problem.

source 5
